import type { OliverAction } from '@/components/shared/OliverContext'

export type CommandMeta = Omit<OliverAction, 'run'>

export const CAMPAIGNS_COMMANDS: CommandMeta[] = [
  {
    id: 'add-campaign',
    label: 'Add Campaign',
    group: 'Create',
    hint: 'Capture campaign strategy, audience, and cadence details',
    aliases: ['new campaign', 'create campaign', 'add campaign'],
  },
  {
    id: 'add-content-draft',
    label: 'Add Content Draft',
    group: 'Create',
    hint: 'Create a new content draft in draft status',
    aliases: ['new content', 'create draft', 'add draft'],
  },
  {
    id: 'add-content-asset',
    label: 'Add Content Asset',
    group: 'Create',
    hint: 'Attach an asset URL or file reference to an existing content item',
    aliases: ['add asset', 'attach asset', 'asset link'],
  },
  {
    id: 'submit-content-review',
    label: 'Submit Content Review',
    group: 'Edit',
    hint: 'Move draft content to Needs Review',
    aliases: ['submit review', 'send to review', 'ready for review'],
  },
  {
    id: 'approve-content',
    label: 'Approve Content',
    group: 'Edit',
    hint: 'Approve Needs Review content into Unclaimed',
    aliases: ['approve review item', 'approve post', 'approve draft'],
  },
  {
    id: 'reject-content',
    label: 'Reject Content',
    group: 'Edit',
    hint: 'Reject Needs Review content back to Draft with reason',
    aliases: ['reject review item', 'send back to draft', 'reject post'],
  },
  {
    id: 'claim-content',
    label: 'Claim Content',
    group: 'Edit',
    hint: 'Find unclaimed content and claim it for yourself',
    aliases: ['claim post', 'claim unclaimed', 'self claim content'],
  },
  {
    id: 'unclaim-content',
    label: 'Unclaim Content',
    group: 'Edit',
    hint: 'Release a claimed content item back to Unclaimed',
    aliases: ['release claim', 'unassign claim', 'unclaim post'],
  },
  {
    id: 'add-calendar-reminder',
    label: 'Add Calendar Reminder',
    group: 'Create',
    hint: 'Create an in-app reminder for claimed content',
    aliases: ['set reminder', 'schedule reminder', 'calendar reminder'],
  },
  {
    id: 'mark-posted',
    label: 'Mark Posted',
    group: 'Edit',
    hint: 'Mark claimed content as Posted and archive it',
    aliases: ['content posted', 'finish post', 'close content'],
  },
  {
    id: 'add-post-url',
    label: 'Add Post URL',
    group: 'Edit',
    hint: 'Attach or update final live URL on claimed or posted content',
    aliases: ['update post url', 'attach post link', 'final url'],
  },
  {
    id: 'add-performance-metrics',
    label: 'Add Performance Metrics',
    group: 'Create',
    hint: 'Capture manual performance stats for a content item',
    aliases: ['log metrics', 'add analytics', 'record performance'],
  },
  {
    id: 'show-campaign-summary',
    label: 'Show Campaign Summary',
    group: 'Search',
    hint: 'Summarize created, approved, claimed, posted, and missed activity',
    aliases: ['campaign summary', 'campaign status', 'report summary'],
  },
  {
    id: 'export-campaign-summary',
    label: 'Export Campaign Summary',
    group: 'Search',
    hint: 'Generate markdown execution summary for reporting',
    aliases: ['export summary', 'download summary', 'campaign export'],
  },
  {
    id: 'open-content-library',
    label: 'Open Content Library',
    group: 'Quick',
    hint: 'Jump to campaign content library and filters',
    aliases: ['content library', 'available content', 'open unclaimed content'],
  },
  {
    id: 'open-unclaimed-content',
    label: 'Open Unclaimed Content',
    group: 'Quick',
    hint: 'Jump to available unclaimed content for claiming',
    aliases: ['unclaimed content', 'available claims', 'open claim queue'],
  },
  {
    id: 'open-my-claimed',
    label: 'Open My Claimed',
    group: 'Quick',
    hint: 'Jump to your claimed posting schedule',
    aliases: ['my claimed', 'my schedule', 'my posting queue'],
  },
  {
    id: 'open-review-queue',
    label: 'Open Review Queue',
    group: 'Quick',
    hint: 'Jump to Needs Review queue',
    aliases: ['review queue', 'needs review', 'pending approvals'],
  },
  {
    id: 'open-calendar',
    label: 'Open Calendar',
    group: 'Quick',
    hint: 'Jump to schedule and missed posting visibility',
    aliases: ['posting calendar', 'schedule view', 'open slots'],
  },
  {
    id: 'open-reports',
    label: 'Open Reports',
    group: 'Quick',
    hint: 'Jump to campaign reporting and export section',
    aliases: ['campaign reports', 'report dashboard', 'reporting section'],
  },
]
